# Generated by Django 5.0.1 on 2024-01-24 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TNC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='genre',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesure',
            name='page_officielle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='year',
            field=models.IntegerField(default=2005, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
            preserve_default=False,
        ),
    ]
