# Generated by Django 5.0.1 on 2024-01-26 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TNC', '0002_mesure_active_mesure_genre_mesure_page_officielle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('mesure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TNC.mesure')),
            ],
            bases=('TNC.mesure',),
        ),
    ]
