# Generated by Django 5.0.1 on 2024-01-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TNC', '0003_commande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
