# Generated by Django 5.0.1 on 2024-01-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TNC', '0005_commande'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
