# Generated by Django 5.0.1 on 2024-01-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TNC', '0008_rename_nom_commande_type_remove_commande_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mesure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TNC.mesure'),
        ),
    ]
