# Generated by Django 5.0.1 on 2024-01-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TNC', '0012_mesure_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='like_new',
        ),
    ]
